// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzLK6ZSx20Gj9239rSaVvFaeA1UHtWxdU',
    appId: '1:988810755372:web:1522d868ecfac9e7a10089',
    messagingSenderId: '988810755372',
    projectId: 'dino-run-a1011',
    authDomain: 'dino-run-a1011.firebaseapp.com',
    storageBucket: 'dino-run-a1011.appspot.com',
    measurementId: 'G-VHZ9ZK7JKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPE1-IscoxO-WRBmBpRVmZCI9IKoVQnFI',
    appId: '1:988810755372:android:3ae087e345f748e1a10089',
    messagingSenderId: '988810755372',
    projectId: 'dino-run-a1011',
    storageBucket: 'dino-run-a1011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJmG0q6uknvniLZ5bLHTb8rJP7iy776eA',
    appId: '1:988810755372:ios:494e03f48cfb3577a10089',
    messagingSenderId: '988810755372',
    projectId: 'dino-run-a1011',
    storageBucket: 'dino-run-a1011.appspot.com',
    iosClientId: '988810755372-73lch73h84495kc7oa0dth4lh4dv6oq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinoRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJmG0q6uknvniLZ5bLHTb8rJP7iy776eA',
    appId: '1:988810755372:ios:275a1ff10c61cbd9a10089',
    messagingSenderId: '988810755372',
    projectId: 'dino-run-a1011',
    storageBucket: 'dino-run-a1011.appspot.com',
    iosClientId: '988810755372-6teu3iglhs14v2ukhasri69np88olhha.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinoRun.RunnerTests',
  );
}
